const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'ui', 'index.html'), 'utf8');
const source = fs.readFileSync(path.join(root, 'ui', 'routing.js'), 'utf8');
const nodeTools = fs.readFileSync(path.join(root, 'ui', 'routing_nodes.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'ui', 'style.css'), 'utf8');
const ids = new Set([...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]));
const referenced = [...source.matchAll(/byId\('([^']+)'\)/g)].map(match => match[1]);

assert.deepEqual([...new Set(referenced.filter(id => !ids.has(id)))], []);
assert.match(html, /data-page="routing"/);
assert.match(html, /id="page-routing"/);
assert.match(source, /preview_routing/);
assert.match(source, /apply_routing/);
assert.match(source, /get_routing_proxies/);
assert.match(source, /select_routing_proxy/);
assert.match(source, /preview_routing_match/);
assert.match(source, /refresh_routing_provider/);
assert.match(source, /function syncProviderNodesFromGroups/);
assert.match(source, /setup\.provider_nodes\[providerId\] = \{ updated_at: updatedAt, nodes \}/);
assert.match(source, /result\.selection_invalid/);
assert.match(source, /原节点失效需重选/);
assert.match(source, /已失效，请重新选择/);
assert.match(source, /preview_routing_provider/);
assert.match(source, /function previewProvider/);
assert.match(source, /function downloadRouteOptions/);
assert.match(source, /'auto', '智能自动更新（推荐）'/);
assert.match(source, /Windows 系统代理/);
assert.match(source, /'system-proxy', 'Windows 系统代理（迁移\/恢复）'/);
assert.match(source, /'custom-proxy', '自定义本地代理（迁移\/恢复）'/);
assert.doesNotMatch(source, /系统代理优先/);
assert.match(source, /download_route: provider\.download_route \|\| 'auto'/);
assert.match(source, /download_proxy: provider\.download_proxy \|\| ''/);
assert.match(source, /user_agent: provider\.user_agent \|\| ''/);
assert.match(source, /result\.download_route/);
assert.match(source, /http:\/\/127\.0\.0\.1:7897/);
assert.match(source, /User-Agent/);
assert.match(source, /不会创建 TUN 或接管流量/);
assert.match(source, /function providerCache/);
assert.match(source, /setup\?\.provider_caches/);
assert.match(source, /cache\.node_count/);
assert.match(source, /不依赖 Clash Verge/);
assert.match(source, /import_routing_provider/);
assert.match(source, /10 \* 1024 \* 1024/);
assert.match(source, /导入 YAML/);
assert.match(css, /\.routing-provider-recovery/);
assert.match(css, /\.routing-provider-import-row/);
assert.match(source, /保存配置/);
assert.match(source, /运行服务仍使用已应用配置/);
assert.match(source, /m7\.5 12\.5 3 3 6\.5-7/);
assert.doesNotMatch(source, /icon\.textContent = ok \? '✓'/);
assert.match(source, /start_preview_routing_test/);
assert.match(source, /start_routing_group_test/);
assert.match(source, /get_routing_test_job/);
assert.match(source, /cancel_routing_test_job/);
assert.doesNotMatch(source, /test_routing_proxy_group/);
assert.doesNotMatch(source, /test_preview_routing_provider/);
assert.match(source, /临时全部测速/);
assert.match(source, /TEST_POLL_MS = 250/);
assert.match(source, /routingTestJobs/);
assert.match(source, /function mergeTestNodes/);
assert.match(source, /function restoreTestResult/);
assert.match(source, /nodeState === 'testing'/);
assert.match(source, /测速中…/);
assert.match(source, /已保留上次结果/);
assert.match(source, /save_proxy_preference/);
assert.match(source, /function preferenceNodeName/);
assert.match(source, /function runtimeGroupUsesPreference/);
assert.match(source, /group\.selected === `\[\$\{provider\.name\}\] \$\{selectedNode\}`/);
assert.match(source, /preferenceNodeName\(node, !!group\?\.preview\)/);
assert.match(source, /saveProxyPreference\(provider\.id, 'manual', preferenceName\)/);
assert.doesNotMatch(source, /saveProxyPreference\(provider\.id, 'manual', node\.name\)/);
assert.match(source, /使用此节点/);
assert.match(source, /自动优选/);
assert.match(source, /selection_mode/);
assert.match(source, /selected_node/);
assert.match(source, /auto_update/);
assert.match(source, /save_proxy_preference\(\s*providerId, mode, nodeName, \{ \.\.\.provider \}\)/);
assert.match(source, /TEST_POLL_MAX_MS/);
assert.match(source, /cancel_routing_test_job\(context\.jobId\)/);
assert.match(source, /provider_nodes/);
assert.match(source, /尚未生成节点快照/);
assert.match(source, /function hydrateProviderNodes/);
assert.match(source, /重新获取订阅/);
assert.match(source, /function openProviderNodes/);
assert.match(source, /'预览节点'/);
assert.match(source, /proxy_providers/);
assert.match(source, /btn-routing-provider-add/);
assert.match(html, /data-routing-tab="overview"/);
assert.match(html, /data-routing-tab="rules"/);
assert.match(html, /data-routing-tab="providers"/);
assert.doesNotMatch(html, /data-routing-tab="nodes"/);
assert.match(html, /data-routing-workbench="nodes"/);
assert.match(html, /role="tablist"/);
assert.match(html, /role="tabpanel"/);
assert.match(html, /id="routing-test-domain"/);
assert.match(html, /id="routing-node-grid"/);
assert.match(html, /id="routing-node-regions"/);
assert.match(html, /id="routing-node-sort"/);
assert.match(html, /id="btn-routing-locate-current"/);
assert.match(html, /<script src="routing_nodes\.js"><\/script>\s*<script src="routing_telemetry\.js"><\/script>\s*<script src="routing\.js"><\/script>/);
assert.match(source, /nodeTools\.regionOptions/);
assert.match(source, /nodeTools\.sortNodes/);
assert.match(source, /function locateCurrentNode/);
assert.match(nodeTools, /function regionCode/);
assert.match(nodeTools, /function sortNodes/);
assert.match(html, /id="routing-test-progress"/);
assert.match(html, /id="routing-test-progress-bar"/);
assert.match(html, /id="btn-routing-test-cancel"/);
assert.match(html, /id="btn-routing-auto-select"/);
assert.match(html, /id="routing-dirty"/);
assert.match(source, /'url-test': '自动测速'/);
assert.match(source, /match_type: 'suffix'/);
assert.match(source, /Windows VPN/);
assert.match(source, /function enhanceRoutingSelect/);
assert.match(source, /trigger\.disabled = select\.disabled/);
assert.match(source, /if \(select\.disabled\) return/);
assert.match(source, /if \(next\.enabled\) \{\s*providerPreviews\.clear\(\)/s);
assert.match(source, /document\.body\.append\(menu\)/);
assert.match(source, /\['ArrowDown', 'ArrowUp', 'Home', 'End'\]/);
assert.match(source, /placeRoutingMenu\(openSelect\)/);
assert.match(source, /aria-selected/);
assert.match(source, /\['ArrowLeft', 'ArrowRight', 'Home', 'End'\]/);
assert.match(source, /aria-activedescendant/);
assert.match(source, /setupInFlight/);
assert.match(source, /bootstrapInFlight/);
assert.match(source, /get_routing_bootstrap/);
assert.match(source, /void loadSetup\(\);/);
assert.match(source, /function nodeHealthDetail/);
assert.match(source, /function nodeHealthSummary/);
assert.match(source, /本次检测未通过/);
assert.doesNotMatch(source, /node\.alive \? '可用' : '不可用'/);
assert.match(source, /appliedConfig/);
assert.match(source, /enabled: rule\.enabled !== false/);
assert.match(source, /routing-node-metadata/);
assert.match(css, /\.routing-test-progress/);
assert.match(css, /\.routing-node-action/);
assert.match(css, /\.routing-node-filterbar/);
assert.match(css, /\.routing-region-chip/);
assert.match(css, /\.routing-node\.located/);
assert.match(css, /\.routing-provider-update-settings/);
assert.match(css, /\.routing-tabs\s*\{[^}]*grid-template-columns:[^;}]*repeat\(4/s);
assert.match(css, /\.routing-tabs\s*\{[^}]*flex-direction:\s*row/s);
assert.match(css, /\.routing-tabs button\s*\{[^}]*width:\s*auto/s);
assert.doesNotMatch(source, /`Windows VPN · \$\{vpn\.name\}`/);
assert.match(html, /id="routing-node-toolbar"/);
assert.match(html, /routing-node-alive[^>]*type="checkbox"[^>]*><i[^>]*><svg[^>]*><path d="m7\.5 12\.5 3 3 6\.5-7"/);
assert.match(source, /去订阅管理/);
assert.match(source, /预览节点/);
console.log('routing UI bridge and fields: ok');
