const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'ui', 'index.html'), 'utf8');
const source = fs.readFileSync(path.join(root, 'ui', 'routing.js'), 'utf8');
const activitySource = fs.readFileSync(path.join(root, 'ui', 'routing_activity.js'), 'utf8');
const nodeTools = fs.readFileSync(path.join(root, 'ui', 'routing_nodes.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'ui', 'style.css'), 'utf8');
const rulesCss = fs.readFileSync(path.join(root, 'ui', 'routing_rules.css'), 'utf8');
const ids = new Set([...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]));
const referenced = [...source.matchAll(/byId\('([^']+)'\)/g)].map(match => match[1]);

const selectInventory = [...html.matchAll(/<select\b([^>]*)>/g)].map(match => ({
  id: match[1].match(/id="([^"]+)"/)?.[1] || '',
  smart: /class="[^"]*smart-select-native/.test(match[1]),
}));
assert.deepEqual(
  selectInventory.filter(item => item.smart).map(item => item.id).sort(),
  ['sms-email-provider', 'sms-method']);
assert.deepEqual(
  selectInventory.filter(item => !item.smart).map(item => item.id).sort(),
  [
    'builtin-rules-type', 'connections-sort', 'proxy-log-level', 'proxy-log-order',
    'routing-builtin-pack', 'routing-capture-mode', 'routing-default', 'routing-interface',
    'routing-auto-policy-tolerance-unit', 'routing-dns-enhanced', 'routing-dns-mode', 'routing-node-group', 'routing-node-sort',
    'routing-proxy-strategy', 'routing-traffic-mode',
  ].sort(),
  '新增业务下拉框必须登记并接入自定义组件，禁止回退为原生 select');
for (const id of [
  'routing-capture-mode', 'routing-traffic-mode', 'routing-interface',
  'routing-proxy-strategy', 'routing-default', 'routing-builtin-pack',
  'routing-dns-mode', 'routing-dns-enhanced',
]) assert.match(source, new RegExp(`'${id}'`));
assert.match(source, /enhanceRoutingSelect\(byId\('builtin-rules-type'\), \{ compact: true \}\)/);
assert.match(source, /enhanceRoutingSelect\(byId\('routing-node-sort'\), \{ compact: true \}\)/);
assert.match(source, /enhanceRoutingSelect\(groupSelect, \{ compact: true \}\)/);
assert.match(source, /enhanceSelect: enhanceRoutingSelect/);
for (const id of ['connections-sort', 'proxy-log-level', 'proxy-log-order']) {
  assert.match(activitySource, new RegExp(`'${id}'`));
}
assert.match(activitySource, /RoutingWorkspace\?\.enhanceSelect\?\.\(byId\(id\), \{ compact: true \}\)/);

assert.deepEqual([...new Set(referenced.filter(id => !ids.has(id)))], []);
assert.match(html, /data-page="routing"/);
assert.match(html, /id="page-routing"/);
for (const page of ['subscriptions', 'nodes', 'rules', 'connections', 'logs']) {
  assert.match(html, new RegExp(`data-page="${page}"`));
  assert.match(html, new RegExp(`id="page-${page}"`));
}
assert.match(source, /preview_routing/);
assert.match(source, /apply_routing/);
assert.match(source, /schema_version: 8/);
assert.match(html, /id="routing-dns-mode"/);
assert.match(html, /id="routing-dns-advanced"/);
assert.match(html, /阿里 DNS \+ DNSPod DoH/);
assert.doesNotMatch(html, /placeholder="[^"]*(?:1\.1\.1\.1|8\.8\.8\.8)/);
assert.match(source, /validate_routing_dns/);
assert.match(source, /parseNameserverPolicy/);
assert.match(source, /DNS_RECOMMENDED/);
assert.match(html, /id="routing-bypass-domains"/);
assert.match(html, /id="routing-bypass-processes"/);
assert.match(html, /id="routing-bypass-cn-direct"/);
assert.match(html, /国内域名不经过系统代理/);
assert.match(html, /class="routing-option-switch routing-cn-bypass-option"/);
assert.match(html, /class="routing-option-switch routing-backup-urls-option"/);
assert.match(html, /补充绕过域名/);
assert.match(html, /用于补充规则包未覆盖的域名/);
assert.match(source, /system_proxy_bypass/);
assert.match(source, /include_cn_direct/);
assert.match(source, /function renderCnBypassSummary/);
assert.match(source, /function splitMaintenanceLines[\s\S]*?\.split\(\/\\r\?\\n\/\)/);
assert.match(source, /bypass → user → builtin/);
assert.match(source, /function preferredNodeGroupId\(\)/);
assert.match(source, /outbound\.startsWith\('proxy:'\)/);
assert.match(source, /selection_mode === 'manual' && String\(item\.selected_node \|\| ''\)\.trim\(\)/);
assert.match(source, /pendingNodeGroup = preferredNodeGroupId\(\)/);
assert.match(source, /GEOIP\(CN\)/);
assert.match(source, /runtime_geoip_fallback/);
assert.match(source, /export_config_backup/);
assert.match(source, /preview_config_restore/);
assert.match(source, /restore_config_backup/);
assert.doesNotMatch(source, /get_routing_config_history|restore_routing_config_history|export_routing_diagnostics|loadConfigHistory|downloadJson|createObjectURL/);
assert.doesNotMatch(html, /routing-config-history|routing-history|btn-routing-diagnostic|routing-restore-file/);
assert.match(html, /<details class="routing-config-transfer">/);
assert.match(source, /配置已导出至：\$\{result.path\}/);
assert.match(source, /if \(result\?\.cancelled\) return/);
assert.match(source, /if \(preview\?\.cancelled\) return/);
assert.match(html, /登录、VPN、邮箱、VLM 和 Controller 凭据始终不会导出/);
assert.doesNotMatch(css, /\.routing-config-history|\.routing-history/);
assert.match(css, /\.routing-option-switch > input:focus-visible \+ i/);
assert.match(css, /\.routing-option-switch > input:checked \+ i/);
assert.match(source, /get_routing_proxies/);
assert.match(source, /select_routing_proxy/);
assert.match(source, /preview_routing_match/);
assert.match(source, /refresh_routing_provider/);
assert.match(source, /function syncProviderNodesFromGroups/);
assert.match(source, /setup\.provider_nodes\[providerId\] = \{ updated_at: updatedAt, nodes \}/);
assert.match(source, /result\.selection_invalid/);
assert.match(source, /原节点失效需重选/);
assert.match(source, /已失效，请重新选择/);
assert.match(source, /preview_routing_provider/);
assert.match(source, /function previewProvider/);
assert.match(source, /function fetchProvider/);
assert.match(source, /fetch\.onclick = \(\) => fetchProvider\(provider\)/);
assert.match(source, /state \|\| runtimeStatus\?\.core_running/);
assert.match(source, /refreshProvider\(provider\.id, true\)/);
assert.match(source, /正在尝试备用下载路径/);
const previewFlow = source.slice(
  source.indexOf('async function previewProvider'),
  source.indexOf('async function importProviderYaml'));
assert.doesNotMatch(previewFlow, /catch \(error\)[\s\S]*providerPreviews\.delete\(provider\.id\)/);
assert.match(previewFlow, /已保留上次节点列表/);
assert.match(source, /function downloadRouteOptions/);
assert.match(source, /'auto', '智能自动更新（推荐）'/);
assert.match(source, /Windows 系统代理/);
assert.match(source, /'system-proxy', 'Windows 系统代理（迁移\/恢复）'/);
assert.match(source, /'custom-proxy', '自定义本地代理（迁移\/恢复）'/);
assert.doesNotMatch(source, /系统代理优先/);
assert.match(source, /download_route: provider\.download_route \|\| 'auto'/);
assert.match(source, /download_proxy: provider\.download_proxy \|\| ''/);
assert.match(source, /user_agent: provider\.user_agent \|\| ''/);
assert.match(source, /result\.download_route/);
assert.match(source, /http:\/\/127\.0\.0\.1:7897/);
assert.match(source, /User-Agent/);
assert.match(source, /不会创建 TUN 或接管流量/);
assert.match(source, /function providerCache/);
assert.match(source, /setup\?\.provider_caches/);
assert.match(source, /cache\.node_count/);
assert.match(source, /不依赖 Clash Verge/);
assert.match(source, /import_routing_provider/);
assert.match(source, /10 \* 1024 \* 1024/);
assert.match(source, /导入 YAML/);
assert.match(css, /\.routing-provider-recovery/);
assert.match(css, /\.routing-provider-import-row/);
assert.match(source, /保存配置/);
assert.match(source, /运行服务仍使用已应用配置/);
assert.match(source, /m7\.5 12\.5 3 3 6\.5-7/);
assert.doesNotMatch(source, /icon\.textContent = ok \? '✓'/);
assert.match(source, /start_preview_routing_test/);
assert.match(source, /start_routing_group_test/);
assert.match(source, /get_routing_test_job/);
assert.match(source, /cancel_routing_test_job/);
assert.doesNotMatch(source, /test_routing_proxy_group/);
assert.doesNotMatch(source, /test_preview_routing_provider/);
assert.match(source, /临时全部测速/);
assert.match(source, /TEST_POLL_MS = 750/);
assert.match(source, /routingTestJobs/);
assert.match(source, /function mergeTestNodes/);
assert.match(source, /function restoreTestResult/);
assert.match(source, /nodeState === 'testing'/);
assert.match(source, /测速中…/);
assert.match(source, /已保留上次结果/);
assert.match(source, /existingCards = new Map\(\[\.\.\.grid\.children\]/);
assert.match(source, /card\.dataset\.nodeKey = nodeKey/);
assert.match(source, /if \(current !== card\) grid\.insertBefore\(card, current \|\| null\)/);
assert.doesNotMatch(source, /grid\.replaceChildren\(\.\.\.nodes\.map/,
  '测速进度刷新必须复用节点卡片，避免 hover 边框反复触发过渡');
assert.match(source, /save_proxy_preference/);
assert.match(source, /function preferenceNodeName/);
assert.match(source, /function runtimeGroupUsesPreference/);
assert.match(source, /group\.selected === `\[\$\{provider\.name\}\] \$\{selectedNode\}`/);
assert.match(source, /preferenceNodeName\(node, !!group\?\.preview\)/);
assert.match(source, /saveProxyPreference\(group\.id, 'manual', preferenceName, null, owner\.id\)/);
assert.doesNotMatch(source, /saveProxyPreference\(provider\.id, 'manual', node\.name\)/);
assert.match(source, /使用此节点/);
assert.match(source, /save_aggregate_proxy_preference/);
assert.match(source, /choose\.disabled = busy \|\| !owner\?\.enabled/);
assert.match(source, /provider\?\.id, provider\?\.enabled, provider\?\.selection_mode/);
assert.match(source, /自动优选/);
assert.match(source, /selection_mode/);
assert.match(source, /selected_node/);
assert.match(source, /auto_update/);
assert.match(source, /save_proxy_preference\(\s*providerId, mode, nodeName, \{ \.\.\.provider \}, policy\)/);
assert.match(source, /TEST_POLL_MAX_MS/);
assert.match(source, /cancel_routing_test_job\(context\.jobId\)/);
assert.match(source, /provider_nodes/);
assert.match(source, /const source = \[runtime, persisted, preview\]/);
assert.match(source, /job\.status === 'completed' && context\.groupId !== 'all'/);
assert.match(source, /尚未生成节点快照/);
assert.match(source, /function hydrateProviderNodes/);
assert.match(source, /重新获取订阅/);
assert.match(source, /function openProviderNodes/);
assert.match(source, /'预览节点'/);
assert.match(source, /proxy_providers/);
assert.match(source, /btn-routing-provider-add/);
assert.match(source, /function providerReferencePlan\(providerId, includeDisabledRules = false\)/);
assert.match(source, /replacement: remaining\.length \? 'proxy' : 'block'/);
assert.match(source, /function replaceProviderReferences\(plan, includeDisabledRules = false\)/);
assert.match(source, /停用后将自动改为\$\{plan\.replacementLabel\}/);
assert.match(source, /replaceProviderReferences\(plan, true\)/);
assert.doesNotMatch(source, /停用后配置将无法通过预检/);
assert.match(html, /data-routing-tab="overview"/);
assert.match(html, /data-routing-tab="rules"/);
assert.match(html, /data-routing-tab="providers"/);
assert.doesNotMatch(html, /data-routing-tab="nodes"/);
assert.match(html, /data-routing-workbench="nodes"/);
assert.match(html, /role="tablist"/);
assert.match(html, /role="tabpanel"/);
assert.match(html, /id="routing-test-domain"/);
assert.match(html, /id="builtin-rules-list"/);
assert.match(html, /id="builtin-rules-search"/);
assert.match(html, /id="builtin-rules-type"/);
assert.match(source, /function renderBuiltinRules/);
assert.match(source, /setup\?\.builtin_rule_packs\?\.\[packId\]/);
assert.match(html, /本地规则包/);
assert.match(source, /detail\.source_file/);
assert.match(source, /当前为全局模式：这些规则仍保留在配置中/);
assert.match(rulesCss, /\.builtin-rule-row/);
assert.match(rulesCss, /\.builtin-rules-list/);
assert.match(html, /id="routing-node-grid"/);
assert.match(html, /id="routing-node-regions"/);
assert.match(html, /id="routing-node-sort"/);
assert.match(html, /id="btn-routing-locate-current"/);
assert.match(html, /<script src="routing_nodes\.js"><\/script>\s*<script src="routing_telemetry\.js"><\/script>\s*<script src="routing_workspace\.js"><\/script>\s*<script src="routing\.js"><\/script>\s*<script src="proxy\.js"><\/script>\s*<script src="routing_activity\.js"><\/script>/);
assert.match(source, /nodeTools\.regionOptions/);
assert.match(source, /nodeTools\.sortNodes/);
assert.match(source, /function locateCurrentNode/);
assert.match(nodeTools, /function regionCode/);
assert.match(nodeTools, /function sortNodes/);
assert.match(html, /id="routing-test-progress"/);
assert.match(html, /id="routing-test-progress-bar"/);
assert.match(html, /id="btn-routing-test-cancel"/);
assert.match(html, /id="btn-routing-auto-select"/);
assert.match(html, /id="routing-auto-policy"/);
assert.match(html, /id="routing-auto-policy-stages"/);
assert.match(html, /data-auto-fallback="reject"/);
assert.match(html, /data-auto-fallback="all"/);
assert.match(source, /function renderAutoPolicy/);
assert.match(source, /function validateAutoPolicyDraft/);
assert.match(source, /preferred_keywords/);
assert.match(source, /latency_tolerance/);
assert.match(source, /latency_tolerance_unit/);
assert.match(source, /selection_mode === 'failure'/);
assert.match(source, /preferred_node/);
assert.match(source, /createKeywordEditor/);
assert.doesNotMatch(source, /autoPolicyWords/);
assert.doesNotMatch(source, /preferred_keywords \|\| \[\]\)\.join\(/);
assert.match(source, /enhanceRoutingSelect\(region, \{ compact: true \}\)/);
assert.match(source, /enhanceRoutingSelect\(mode, \{ compact: true \}\)/);
assert.match(source, /enhanceRoutingSelect\(preferredNode, \{ compact: true \}\)/);
assert.match(source, /enhanceRoutingSelect\(byId\('routing-auto-policy-tolerance-unit'\), \{ compact: true \}\)/);
assert.match(css, /\.routing-auto-policy-stage/);
assert.match(css, /\.routing-auto-policy-stage \.field\s*\{[^}]*width:\s*auto/s);
assert.match(css, /\.routing-auto-policy-keywords\s*\{[^}]*grid-template-columns:\s*1fr 1fr/s);
assert.match(html, /id="routing-dirty"/);
assert.match(source, /'url-test': '自动测速'/);
assert.match(source, /match_type: 'suffix'/);
assert.match(source, /Windows VPN/);
assert.match(source, /function enhanceRoutingSelect/);
assert.match(source, /trigger\.disabled = select\.disabled/);
assert.match(source, /if \(select\.disabled\) return/);
assert.match(source, /acceptApplyResult\(result\);\s*hydrateProviderNodes\(\)/s);
assert.match(source, /document\.body\.append\(menu\)/);
assert.match(source, /\['ArrowDown', 'ArrowUp', 'Home', 'End'\]/);
assert.match(source, /placeRoutingMenu\(openSelect\)/);
assert.match(source, /aria-selected/);
assert.match(source, /\['ArrowLeft', 'ArrowRight', 'Home', 'End'\]/);
assert.match(source, /aria-activedescendant/);
assert.match(source, /setupInFlight/);
assert.match(source, /bootstrapInFlight/);
assert.match(source, /get_routing_bootstrap/);
assert.match(source, /void loadSetup\(\);/);
assert.match(source, /function nodeHealthDetail/);
assert.match(source, /function nodeHealthSummary/);
assert.match(source, /本次检测未通过/);
assert.doesNotMatch(source, /node\.alive \? '可用' : '不可用'/);
assert.match(source, /appliedConfig/);
assert.match(source, /enabled: rule\.enabled !== false/);
assert.match(source, /routing-node-metadata/);
assert.match(css, /\.routing-test-progress/);
assert.match(css, /\.routing-node-action/);
assert.match(css, /\.routing-node-filterbar/);
assert.match(css, /\.routing-region-chip/);
assert.match(css, /\.routing-node\.located/);
assert.match(css, /\.routing-provider-update-settings/);
assert.match(source, /订阅更新间隔（分钟）/);
assert.match(source, /自动测速间隔（分钟）/);
assert.match(source, /speedtestInterval\.min = '1'; speedtestInterval\.max = '1440'; speedtestInterval\.step = '1'/);
assert.match(source, /speedtestInterval\.disabled = busy/);
assert.doesNotMatch(source, /speedtestInterval\.disabled = [^;]*auto_update/);
assert.match(source, /provider\.speedtest_interval = Number\(speedtestInterval\.value\) \* 60; syncDirty\(\)/);
assert.match(source, /provider\.speedtest_interval \?\?= 300/);
assert.match(source, /speedtest_interval: 300/);
assert.match(css, /\.routing-tabs\s*\{[^}]*grid-template-columns:[^;}]*repeat\(4/s);
assert.match(css, /\.routing-tabs\s*\{[^}]*flex-direction:\s*row/s);
assert.match(css, /\.routing-tabs button\s*\{[^}]*width:\s*auto/s);
assert.doesNotMatch(source, /`Windows VPN · \$\{vpn\.name\}`/);
assert.match(html, /id="routing-node-toolbar"/);
assert.match(html, /routing-node-alive[^>]*type="checkbox"[^>]*><i[^>]*><svg[^>]*><path d="m7\.5 12\.5 3 3 6\.5-7"/);
assert.match(source, /去订阅管理/);
assert.match(source, /预览节点/);
console.log('routing UI bridge and fields: ok');
