const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'ui', 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'ui', 'app.js'), 'utf8');
const routing = fs.readFileSync(path.join(root, 'ui', 'routing.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'ui', 'style.css'), 'utf8');
const desktop = fs.readFileSync(
  path.join(root, 'core', 'windows_desktop.py'), 'utf8');
const main = fs.readFileSync(path.join(root, 'main.py'), 'utf8');
const apiSource = fs.readFileSync(path.join(root, 'api.py'), 'utf8');

const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
const duplicateIds = [...new Set(ids.filter((id, index) => ids.indexOf(id) !== index))];
const referencedIds = [...app.matchAll(/\$\('([^']+)'\)/g)].map(match => match[1]);
const missingIds = [...new Set(referencedIds.filter(id => !ids.includes(id)))];
assert.deepEqual(duplicateIds, []);
assert.deepEqual(missingIds, []);
assert.equal((css.match(/\{/g) || []).length, (css.match(/\}/g) || []).length);

assert.match(html, /立即处理授权/);
assert.match(html, /id="btn-br-automation" class="btn accent"[^>]*>执行自动化<\/button>/);
assert.match(html, /class="browser-command-actions"/);
assert.doesNotMatch(html, />立即续期</);
assert.match(html, /授权流程执行期间可随时中断/);
assert.match(html, /<details class="help-section" open>/);
assert.match(html, /id="log-empty"/);
assert.match(html, /id="toast" role="status" aria-live="polite"/);
assert.match(html, /id="ov-startup"/);
assert.match(html, /id="ov-tray"/);
assert.match(html, /id="ov-hotkeys"/);
assert.match(html, /id="ov-lightweight"/);
assert.match(html, /未完整配置时将直接转为人工验证/);
assert.match(html, /<span>自动化配置<\/span>/);
const automationNav = html.match(/<button type="button" data-page="vlm">([\s\S]*?)<\/button>/)?.[1] || '';
assert.match(automationNav, /m4 20 11-11/);
assert.match(automationNav, /M18 2v4M16 4h4/);
assert.doesNotMatch(automationNav, /M4 7h10M18 7h2/);
assert.match(html, /id="sms-method"/);
assert.match(html, /id="smsmodal"[^>]*role="dialog"[^>]*aria-modal="true"/);
assert.match(html, /id="sms-lead"/);
assert.match(html, /id="sms-callout"/);
assert.match(html, /邮箱转发（IMAP）/);
assert.match(html, /class="smart-select method-select"/);
assert.match(html, /class="smart-select compact"/);
assert.match(html, /关闭<b>显示撰写表单<\/b>/);
assert.match(html, /不依赖邮件未读状态/);
assert.match(html, /Android SmsForwarder 邮箱转发/);
assert.match(html, /smtp\.qq\.com/);
assert.match(html, /\{短信内容\}/);
assert.match(html, /单击托盘图标恢复/);
assert.doesNotMatch(html, /双击托盘图标/);
assert.match(html, /id="ov-active-connections"/);
assert.match(html, /id="ov-hours">待同步<\/strong>/);
assert.match(html, /id="ov-renew-hours">待同步<\/strong>/);
assert.match(app, /authorization\.expires_at_text/);
assert.match(app, /\['queued', 'connecting', 'verifying'\]/);
assert.match(html, /id="btn-disconnect-all"/);
assert.doesNotMatch(html, /id="btn-default-more"/);
assert.match(html, /id="connectmodal"/);
assert.match(html, /切换连接/);
assert.match(html, /同时连接/);
assert.match(html, /默认 VPN/);
assert.match(html, /class="status-ribbon"/);
assert.match(html, /class="overview-workspace"/);
assert.match(html, /class="connection-hero"/);
assert.match(html, /id="ip-overview-title">网络出口/);
assert.match(html, /id="ip-local-address"/);
assert.match(html, /id="ip-domestic-address"/);
assert.match(html, /id="ip-overseas-address"/);
assert.match(html, /id="btn-refresh-ip"/);
assert.equal((html.match(/class="ip-copy"/g) || []).length, 3);
assert.match(html, /class="automation-matrix"/);
const automationMatrix = html.slice(
  html.indexOf('<aside class="automation-matrix">'),
  html.indexOf('</aside>', html.indexOf('<aside class="automation-matrix">')));
assert.match(automationMatrix, /id="ov-tray"/);
assert.match(automationMatrix, /id="ov-hotkeys"/);
assert.match(automationMatrix, /id="ov-lightweight"/);
assert.match(automationMatrix, /id="btn-repair"/);
assert.match(automationMatrix, /class="setting-row automation-last-setting"/);
assert.ok(automationMatrix.indexOf('id="ov-tray"') < automationMatrix.indexOf('id="btn-repair"'));
assert.doesNotMatch(html, /class="overview-maintenance"/);
assert.match(html, /id="ov-renew-stages"/);
assert.match(html, /id="ov-renew-progress" class="renewal-progress" max="4"/);
assert.equal((html.match(/data-step="[1-5]"/g) || []).length, 5);
assert.equal((html.match(/class="nav-icon"/g) || []).length, 12);
assert.equal((html.match(/<svg class="nav-icon"/g) || []).length, 12);
assert.match(html, /class="section-icon"[^>]*viewBox="0 0 24 24"/);
assert.match(html, /class="setting-icon"[^>]*><svg viewBox="0 0 24 24"/);
assert.equal((html.match(/class="eye"/g) || []).length, 5);
assert.equal((html.match(/class="eye"[^>]*aria-pressed="false"[^>]*><svg/g) || []).length, 5);
assert.doesNotMatch(html, /class="eye"[^>]*>显示<\/button>/);
assert.match(routing, /url\.type = 'text'/);
assert.match(routing, /url\.className = 'routing-provider-url'/);
assert.doesNotMatch(routing, /toggleSecret\(url, eye\)/);

assert.match(app, /中断授权流程/);
assert.match(app, /function handleRenewalAction/);
assert.match(app, /中断自动化/);
assert.match(app, /\$\('btn-br-automation'\)\.onclick = handleRenewalAction/);
assert.match(app, /tone: 'warning'/);
assert.match(app, /`show toast-\$\{tone\}`/);
assert.match(app, /\['success', 'error', 'warning', 'info'\]/);
assert.match(app, /classList\.add\('toast-icon-success'\)/);
assert.match(app, /<svg viewBox="0 0 24 24"><path d="m7\.5 12\.5 3 3 6\.5-7"\/><\/svg>/);
assert.match(app, /btn-confirm-cancel.*focus/s);
assert.match(app, /set_startup_enabled/);
assert.match(app, /function bindInputModality/);
assert.match(app, /function bindSecretToggles/);
assert.match(app, /function setSecretToggleState/);
assert.match(app, /function concealSecret/);
assert.match(app, /button\.setAttribute\('aria-pressed', String\(revealed\)\)/);
assert.match(app, /M2\.8 12s3\.2-5 9\.2-5/);
assert.match(app, /M3\.5 15\.5s3-4 8\.5-4/);
assert.match(app, /document\.body\.classList\.add\('keyboard-navigation'\)/);
assert.match(app, /document\.body\.classList\.remove\('keyboard-navigation'\)/);
assert.match(app, /api\(\)\.test_sms_email\(\)/);
assert.match(app, /function syncSmsModalCopy/);
assert.match(app, /正在通过 IMAP 邮箱捕获验证码/);
assert.match(app, /确认修复 VPN 服务/);
assert.match(app, /断开并修复/);
assert.match(app, /const stageNumber = index \+ 1/);
assert.match(app, /const done = completed \|\| stageNumber < currentStep/);
assert.doesNotMatch(app, /远端列表已同步，无需刷新页面/);
assert.match(app, /imap\.mail\.me\.com/);
assert.match(app, /function bindSmartSelect/);
assert.match(app, /close_to_tray/);
assert.match(app, /global_hotkeys_enabled/);
assert.match(app, /lightweight_mode/);
assert.match(app, /cxvpn:desktop-action/);
assert.match(css, /body\.lightweight-mode/);
assert.match(app, /api\(\)\.connect_vpn\(name, selectedMode, !!options\.afterAuthorization\)/);
assert.match(app, /api\(\)\.disconnect_vpn\(name\)/);
assert.match(app, /api\(\)\.disconnect_all\(\)/);
assert.doesNotMatch(app, /btn-default-more/);
assert.match(app, /renderVpnConnections/);
assert.match(app, /createConnectionRow/);
assert.match(app, /createEmptyConnectionSlot/);
const createConnectionRow = app.slice(
  app.indexOf('function createConnectionRow'),
  app.indexOf('function createEmptyConnectionSlot'));
const createEmptyConnectionSlot = app.slice(
  app.indexOf('function createEmptyConnectionSlot'),
  app.indexOf('function formatDuration'));
assert.match(createConnectionRow, /moreButton\.onclick = \(\) => openModal\(profile\)/);
assert.doesNotMatch(createConnectionRow, /goToPage\('vpns'\)/);
assert.match(createEmptyConnectionSlot, /button\.onclick = \(\) => openModal\(null\)/);
assert.doesNotMatch(createEmptyConnectionSlot, /goToPage\('vpns'\)/);
assert.match(app, /Math\.max\(5, rows\.length\)/);
assert.match(app, /ov-default-server/);
assert.match(app, /syncVpnUi\(\{ forceRefresh: true, refreshConfig: true \}\)/);
assert.match(app, /VPN_STATUS\.profiles/);
assert.match(app, /button\.innerHTML = original/);
assert.match(app, /updateRepairState/);
assert.match(html, /id="m-user"/);
assert.match(html, /id="m-pass"/);
assert.match(html, /id="m-l2tp-key"/);
assert.match(html, /id="m-ipv4-gateway"/);
assert.match(html, /id="m-ipv6-gateway"/);
assert.match(html, /远程默认网关/);
assert.match(app, /ov-renew-stages/);
assert.match(app, /setConnectionButtonBusy/);
assert.match(app, /connection-action-spinner/);
assert.match(app, /M12 3v8/);
assert.doesNotMatch(app, /<rect x="8" y="8" width="8" height="8" rx="1"/);
assert.match(app, /Math\.max\(0, Math\.min\(4, currentStep - 1\)\)/);
assert.match(app, /route_conflicts/);
assert.match(app, /ensureVpnsLoaded\(\{ background: true \}\)/);
assert.match(app, /if \(vpnListReady\) return Promise\.resolve\(VPN_LIST\)/);
assert.match(app, /api\(\)\.list_vpns\(forceRefresh\)/);
assert.match(app, /forceRefresh: true/);
const finishConnectionAction = app.slice(
  app.indexOf('async function finishConnectionAction'),
  app.indexOf('async function saveVpnModal'));
assert.match(finishConnectionAction, /updateOverview\(state, status\)/);
assert.doesNotMatch(finishConnectionAction, /renderVpnList/);
assert.doesNotMatch(finishConnectionAction, /reloadVpns/);
assert.match(app, /function setVpnProfiles/);
assert.match(app, /setVpnProfiles\(snapshotProfiles, \{ render: curPage === 'vpns' \}\)/);
assert.match(app, /if \(vpnListReady\) renderVpnList\(VPN_LIST\)/);
assert.match(app, /showLoading: !vpnListReady/);
assert.match(app, /row\.dataset\.vpnKey !== key/);
assert.match(app, /VPN 列表刷新失败，已保留当前内容/);
assert.doesNotMatch(app, /connect_vpn_interactive/);
assert.doesNotMatch(app, /completePendingCredentialValidation/);
assert.doesNotMatch(app, /待授权验证/);
assert.match(app, /正在将账号密码同步到 Windows/);
assert.match(app, /btn\('已默认', 'mini default-state'/);
assert.match(app, /ipv4DefaultGateway, ipv6DefaultGateway/);
assert.match(app, /function gatewaySummary/);
assert.match(app, /function activeDefaultRouteLabel/);
assert.match(app, /state\.connection_action/);
assert.match(app, /授权后重连中/);
assert.match(app, /自动连接中/);
assert.match(app, /CFG\.renew_hours \|\| 7/);
assert.match(app, /showConfiguredVpnPreview\(\)/);
assert.match(app, /function refreshIpInfo/);
assert.match(app, /api\(\)\.get_ip_info\(!!forceRefresh\)/);
assert.match(app, /if \(snapshot\.ip_info\) renderIpInfo\(snapshot\.ip_info\)/);
assert.doesNotMatch(app, /ipInfoForceRefreshQueued/);
assert.match(app, /status\.textContent = '部分为旧数据'/);
assert.match(app, /`旧数据 · \$\{baseLocation\}`/);
assert.match(app, /function copyIpAddress/);
assert.match(app, /configuredVpnPreviewProfiles/);
assert.match(app, /pending_system_check: true/);
assert.match(app, /已从 config\.json 读取，正在核对 Windows VPN 状态/);
assert.match(app, /await api\(\)\.ui_ready\(\)/);
assert.match(app, /<div class="vpn-actions"><\/div>/);

assert.match(css, /\.settings-card-head/);
assert.match(css, /\.smart-select-menu button\.selected/);
assert.match(css, /\.help-section\[open\]/);
assert.match(css, /grid-template-columns: minmax\(0, 1fr\) 88px 20px/);
assert.match(css, /\.browser-command-actions/);
assert.match(css, /#toast\.toast-success/);
assert.match(css, /#toast\.toast-error/);
assert.match(css, /\.toast-icon-success svg/);
assert.match(css, /stroke-linecap: round; stroke-linejoin: round/);
assert.match(css, /@keyframes toast-countdown/);
assert.match(css, /--scrollbar-track:/);
assert.match(css, /--scrollbar-thumb-hover:/);
assert.match(css, /scrollbar-color: var\(--scrollbar-thumb\) var\(--scrollbar-track\)/);
assert.match(css, /::-webkit-scrollbar\s*\{[^}]*width: var\(--scrollbar-size\);[^}]*height: var\(--scrollbar-size\)/s);
assert.match(css, /::-webkit-scrollbar-thumb:hover/);
assert.match(css, /::-webkit-scrollbar-thumb:active/);
assert.match(css, /::-webkit-scrollbar-button\s*\{[^}]*display: none;[^}]*width: 0;[^}]*height: 0;/s);
assert.match(css, /::-webkit-scrollbar-corner\s*\{ background: transparent; \}/);
assert.match(css, /\.builtin-rules-list,[\s\S]*\.proxy-log-list \{ scrollbar-gutter: stable; \}/);
assert.match(css, /\.active-connection/);
assert.match(css, /\.connect-mode-options/);
assert.match(css, /grid-template-columns: 52px 70px 52px 52px 52px/);
assert.match(css, /\.vpn-actions \.default-state:disabled/);
assert.match(css, /input:not\(\[type=checkbox\]\):focus, select:focus, textarea:focus/);
assert.match(css, /border-color: rgba\(34,211,238,\.78\); box-shadow: none; outline: none/);
assert.match(css, /\.dd-btn:focus, \.dd-btn:focus-visible/);
assert.doesNotMatch(css, /input:focus, select:focus \{ border-color: var\(--acc1\); box-shadow:/);
assert.match(css, /\.nav-icon/);
assert.match(css, /Segoe Fluent Icons/);
assert.match(css, /stroke-linecap: round/);
assert.match(css, /main \{ min-width: 0; flex: 1; overflow-x: hidden; overflow-y: auto;/);
assert.match(css, /\.renewal-strip/);
assert.match(css, /\.renewal-stages li\.current::after/);
assert.match(css, /@keyframes connection-spin/);
assert.match(css, /\.connection-slot-empty/);
assert.match(css, /\.connection-hero/);
assert.match(css, /\.ip-overview/);
assert.match(css, /\.ip-egress-grid/);
assert.match(css, /\.overview-workspace[\s\S]*gap: 12px/);
assert.match(css, /\.connection-hero[\s\S]*padding: 0 4px 12px 8px/);
assert.match(css, /\.connection-collection[\s\S]*padding: 17px 4px 0 8px/);
assert.match(css, /\.ip-address-line strong[\s\S]*clamp\(13px, 1\.08vw, 16px\)/);
assert.match(css, /@media \(max-height: 920px\)[\s\S]*main \{ padding-bottom: 20px; \}/);
assert.match(css, /@media \(max-height: 820px\)/);
assert.match(css, /@media \(max-height: 820px\)[\s\S]*padding-top: 16px; padding-bottom: 8px/);
assert.match(css, /\.connection-hero \{ min-height: 228px; padding-bottom: 8px; \}/);
assert.match(css, /\.renewal-strip \{ min-height: 86px;/);
assert.match(css, /@media \(max-height: 700px\)[\s\S]*padding-top: 12px; padding-bottom: 4px/);
assert.match(css, /body\.keyboard-navigation nav button:focus-visible/);
assert.match(css, /\.automation-matrix \.automation-last-setting \{ border-bottom: 0; \}/);
assert.doesNotMatch(css, /\.overview-maintenance/);
assert.match(css, /\.vpn-routing-settings/);
assert.match(css, /\.gateway-setting/);
assert.match(css, /\.eye svg/);
assert.match(css, /\.eye\.is-revealed/);
assert.match(css, /\.connection-issue\.active/);

assert.match(desktop, /notify\.MouseClick \+= self\._on_mouse_click/);
assert.doesNotMatch(desktop, /notify\.DoubleClick/);
assert.match(html, /<title>CXVPNTools<\/title>/);
assert.match(html, /<h1>CXVPN<span>Tools<\/span><\/h1>/);
assert.match(css, /\.logo-text h1 \{[\s\S]*white-space: nowrap/);
assert.match(css, /\.logo-text h1 span \{[\s\S]*border: 1px solid rgba\(34, 211, 238, \.24\)/);
assert.match(desktop, /WINDOW_TITLE = 'CXVPNTools'/);
assert.match(main, /WINDOW_TITLE, ui, js_api=api/);
assert.doesNotMatch(`${html}\n${desktop}\n${main}`, /CX VPN 管理器|MANAGER/);
assert.match(desktop, /class SingleInstanceGuard/);
assert.match(main, /hidden=True/);
assert.match(main, /win\.events\.loaded \+= on_loaded/);
assert.match(main, /initial_ui_ready\.wait\(5\)/);
assert.match(apiSource, /def ui_ready\(self\):/);

console.log('ui polish structure and status semantics: ok');
