const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../ui/routing.js'), 'utf8');
const start = source.indexOf('  function physicalInterfaceCheck(');
const end = source.indexOf('  function fillForm()', start);
const context = {};
vm.createContext(context);
vm.runInContext(source.slice(start, end), context);
const check = (selected, rows) => JSON.parse(JSON.stringify(context.physicalInterfaceCheck(selected, rows)));
assert.deepEqual(check('', [{name: 'WLAN'}]), [true, '物理出口', '自动选择 · 当前 WLAN']);
assert.equal(check('以太网', [{name: 'WLAN'}])[0], false);
assert.match(check('以太网', [{name: 'WLAN'}])[2], /指定接口 以太网.*WLAN/);
assert.equal(check('WLAN', [{name: 'WLAN'}])[0], true);
assert.match(check('', [])[2], /当前没有可用物理默认接口/);
assert.equal(check('', [])[0], false);
assert.equal(check('网卡e\u0301\u{1F1E8}\u{1F1F3}', [{name: '网卡e\u0301\u{1F1E8}\u{1F1F3}'}])[0], true);
assert.match(source, /interfaces\.append\(option\('', '自动选择（跟随物理网络）'\)\)/);
assert.match(source, /interfaces\.append\(option\(routingConfig\.physical_interface/);
assert.match(source, /interfaces\.value = routingConfig\.physical_interface \|\| ''/);
console.log('automatic/fixed/unavailable physical interface UI: ok');
